// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty;

(function() {
  var Dag, Node, isObjectEmpty;
  isObjectEmpty = function(x) {
    var v;
    for (v in x) {
      if (!__hasProp.call(x, v)) continue;
      return false;
    }
    return true;
  };
  Node = function(value) {
    this.value = value;
    this.parents = Object.create(null);
    this.children = Object.create(null);
    return this;
  };
  Node.prototype = {
    addParent: function(node) {
      return this.parents[node.value] = node;
    },
    addChild: function(node) {
      return this.children[node.value] = node;
    }
  };
  Dag = function() {
    this.nodes = Object.create(null);
    return this;
  };
  Dag.prototype = {};
  Dag.prototype.before = function(a, b) {
    var nodeA, nodeB, typeA, typeB;
    typeA = typeof a;
    if (!(typeA === 'string' || typeA === 'number')) {
      throw new TypeError("argument a must be a string or number but is " + typeA);
    }
    typeB = typeof b;
    if (!(typeB === 'string' || typeB === 'number')) {
      throw new TypeError("argument b must be a string or number but is " + typeB);
    }
    if (a === b) {
      throw new Error('arguments must not be equal');
    }
    if (this.isBefore(b, a)) {
      throw new Error("trying to set `" + a + "` -> `" + b + "` but already `" + b + "` -> `" + a + "`");
    }
    nodeA = this.nodes[a];
    if (nodeA == null) {
      nodeA = new Node(a);
      this.nodes[a] = nodeA;
    }
    nodeB = this.nodes[b];
    if (nodeB == null) {
      nodeB = new Node(b);
      this.nodes[b] = nodeB;
    }
    nodeA.addChild(nodeB);
    nodeB.addParent(nodeA);
    return this;
  };
  Dag.prototype.isIn = function(x) {
    return this.nodes[x] != null;
  };
  Dag.prototype.isBefore = function(a, b) {
    var child, key, nextNodes, node, nodeA, nodeB, nodes, that, _i, _len, _ref;
    that = this;
    nodeA = this.nodes[a];
    nodeB = this.nodes[b];
    if ((nodeA == null) || (nodeB == null)) {
      return false;
    }
    nodes = [nodeA];
    while (nodes.length !== 0) {
      nextNodes = [];
      for (_i = 0, _len = nodes.length; _i < _len; _i++) {
        node = nodes[_i];
        if (node.children[b] != null) {
          return true;
        }
        _ref = node.children;
        for (key in _ref) {
          child = _ref[key];
          nextNodes.push(child);
        }
      }
      nodes = nextNodes;
    }
    return false;
  };
  Dag.prototype.elements = function() {
    return Object.keys(this.nodes);
  };
  Dag.prototype.parentless = function() {
    var elements, key, node, _ref;
    elements = [];
    _ref = this.nodes;
    for (key in _ref) {
      node = _ref[key];
      if (isObjectEmpty(node.parents)) {
        elements.push(node.value);
      }
    }
    return elements;
  };
  Dag.prototype.childless = function() {
    var elements, key, node, _ref;
    elements = [];
    _ref = this.nodes;
    for (key in _ref) {
      node = _ref[key];
      if (isObjectEmpty(node.children)) {
        elements.push(node.value);
      }
    }
    return elements;
  };
  Dag.prototype.whereAllParentsIn = function(xs) {
    var allParentsIn, child, k, key, node, parentValue, resultSet, results, v, x, xsSet, _i, _j, _len, _len1, _ref;
    xsSet = Object.create(null);
    for (_i = 0, _len = xs.length; _i < _len; _i++) {
      x = xs[_i];
      xsSet[x] = true;
    }
    resultSet = Object.create(null);
    for (_j = 0, _len1 = xs.length; _j < _len1; _j++) {
      x = xs[_j];
      node = this.nodes[x];
      if (node == null) {
        throw new Error("searching whereAllParentsIn of `" + x + "` which is not in graph");
      }
      _ref = node.children;
      for (key in _ref) {
        child = _ref[key];
        if (resultSet[key] != null) {
          continue;
        }
        allParentsIn = true;
        for (parentValue in child.parents) {
          if (xsSet[parentValue] == null) {
            allParentsIn = false;
            break;
          }
        }
        resultSet[key] = allParentsIn;
      }
    }
    results = [];
    for (k in resultSet) {
      v = resultSet[k];
      if (v) {
        results.push(k);
      }
    }
    return results;
  };
  if (typeof window !== "undefined" && window !== null) {
    return window.Vorrang = Dag;
  } else if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    return module.exports = Dag;
  } else {
    throw new Error('either the `window` global or the `module.exports` global must be present');
  }
})();
